name: Build ARM

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04] # ARM builds hanya didukung di Linux
        arch: [arm32, arm64] # Definisikan arsitektur
        build-type: [Debug, Release]

    runs-on: ubuntu-latest
    env:
      BUILD_TYPE: ${{ matrix.build-type }}
      CMAKE_BUILD_PARALLEL_LEVEL: 2
      
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Set env
      run: echo "REPO_TAG=$(git describe --tags --always)" >> $GITHUB_ENV
      shell: bash

    - name: Run ARM build
      uses: pguyot/arm-runner-action@v2.5.2
      with:
        base_image: ${{ matrix.arch == 'arm32' && 'arm32v7/ubuntu:20.04' || 'arm64v8/ubuntu:20.04' }}
        image_additional_mb: 10000
        bind_mount_repository: true
        cpu: cortex-a7
        commands: |
            apt-get update && apt-get install -y gcc g++ cmake python3-pip
            python3 -m pip install --upgrade pip
            pip install conan==1.57.0
            conan remote add conan-transit-legacy https://api.bintray.com/conan/conan/conan-transit
            mkdir -p build && cd build
            cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} -DDCC_VERSION="${{ env.REPO_TAG }}"
            cmake --build .
            mkdir -p /artifacts && cp -r . /artifacts

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: discord-connector-${{ env.REPO_TAG }}-${{ matrix.arch }}-${{ matrix.build-type }}
        path: /artifacts
